"""create_users_and_chats

Revision ID: 86dc2d026271
Revises: 
Create Date: 2024-02-26 15:50:23.613642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dc2d026271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('chats_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chats_users_chat_id_chats')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_users_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name=op.f('pk_chats_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats_users')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
